"""Protocol E (0.4.17-E) — integrated TFNE composition."""

from .e0_protocol import (
    E0_SPEC_PATH,
    PROTOCOL_ID,
    load_e0_spec,
    validate_e0_spec,
)
from .e0_1_protocol import (
    E0_1_SPEC_PATH,
    e0_1_ladder_ids,
    load_e0_1_spec,
    validate_e0_1_spec,
)
from .e1_protocol import (
    E1_EXECUTION_RECEIPT_PATH,
    E1_SPEC_PATH,
    load_e1_spec,
    validate_e1_spec,
)
from .e2_protocol import (
    E2_EXECUTION_RECEIPT_PATH,
    E2_SPEC_PATH,
    e2_delay_class_ids,
    e2_gate_ids,
    load_e2_spec,
    validate_e2_spec,
)
from .e2_execution import (
    assert_no_compile_drift,
    attach_provenance_class_delays,
    build_e2_model,
    build_typed_delay_table,
    delay_step_occupancy,
    hierarchy_fingerprint,
    load_e2_execution_receipt,
    run_e2_delayed_coupling,
    verify_delayed_continuation,
    verify_delay_ownership,
    write_e2_execution_receipt,
)
from .e3_protocol import (
    E3_SPEC_PATH,
    e3_gate_ids,
    e3_owner_flat_indices,
    load_e3_spec,
    resolve_owner_indices_from_e1_identity,
    validate_e3_spec,
)
from .e1_execution import (
    build_edge_provenance_table,
    build_e1_configuration,
    build_identity_map,
    identity_round_trip_ok,
    load_e1_execution_receipt,
    run_e1_hierarchy_runtime,
    verify_connectivity_ownership,
    write_e1_execution_receipt,
)

__all__ = [
    "PROTOCOL_ID",
    "E0_SPEC_PATH",
    "E0_1_SPEC_PATH",
    "E1_SPEC_PATH",
    "E1_EXECUTION_RECEIPT_PATH",
    "load_e0_spec",
    "validate_e0_spec",
    "load_e0_1_spec",
    "validate_e0_1_spec",
    "e0_1_ladder_ids",
    "load_e1_spec",
    "validate_e1_spec",
    "build_e1_configuration",
    "build_identity_map",
    "build_edge_provenance_table",
    "identity_round_trip_ok",
    "verify_connectivity_ownership",
    "run_e1_hierarchy_runtime",
    "write_e1_execution_receipt",
    "load_e1_execution_receipt",
    "E2_SPEC_PATH",
    "load_e2_spec",
    "validate_e2_spec",
    "e2_delay_class_ids",
    "e2_gate_ids",
    "E2_EXECUTION_RECEIPT_PATH",
    "build_e2_model",
    "attach_provenance_class_delays",
    "assert_no_compile_drift",
    "hierarchy_fingerprint",
    "build_typed_delay_table",
    "delay_step_occupancy",
    "verify_delay_ownership",
    "verify_delayed_continuation",
    "run_e2_delayed_coupling",
    "write_e2_execution_receipt",
    "load_e2_execution_receipt",
    "E3_SPEC_PATH",
    "load_e3_spec",
    "validate_e3_spec",
    "e3_gate_ids",
    "e3_owner_flat_indices",
    "resolve_owner_indices_from_e1_identity",
]
