"""Visualization package for jaxfne.

Static, NumPy-isolated graphics, raster, trace, and PSD plots.
Fully de-allocated from the active JAX tracer tree.
"""
from __future__ import annotations

from .core import FigureResult, require_matplotlib, prepare_static_plot_matrix, close_all
from .rasters import plot_spike_rasters, raster, raster_with_meta
from .traces import (
    plot_continuous_traces,
    vm,
    vm_with_meta,
    rate,
    rate_with_meta,
    source,
    source_with_meta,
    lfp,
    lfp_with_meta,
    csd,
    csd_with_meta,
    lfp_traces,
    csd_traces,
    eeg,
    meg,
    emm,
    summary,
    summary_with_meta,
    parameter_sweep_heatmap,
    parameter_sweep_lines,
    multi_trace,
    dual_voltage_panel,
    coupled_vs_uncoupled_ei,
)
from .spectra import (
    plot_spectrogram_profiles,
    psd,
    psd_with_meta,
    spectrogram,
    spectrogram_with_meta,
    windowed_band_power,
)
from .fields import (
    plot_laminar_field_interpolation,
    spectrolaminar,
    spectrolaminar_suite,
    bandpower,
    laminar_profile,
    layer_celltype_counts,
    connectivity,
    connectivity_matrix,
    multi_area_layout,
    objective_report,
    ei_circuit_diagram,
)
from .network3d import (
    circuit3d,
    geometry3d,
    column_geometry,
    visualize_network_3d,
)
from . import tutorial_panels
from .tutorial_panels import (
    visualize_laminar_column_3d,
    activity_trace_suite,
    spectrolaminar_suite_3panel,
)
from .raster_arrays import raster_from_arrays
from .plasticity_viz import plot_stdp_adaptation_suite
from .layout import cumulative_stack_offsets, cumulative_panel_extents
from .tutorial_array_plots import (
    plot_population_raster,
    plot_population_rate_array,
    plot_voltage_samples_array,
    plot_connectivity_matrix_array,
    plot_laminar_readout_array,
    plot_spectrolaminar_power_array,
)
from . import plotly
from .canonical import (
    plot_network_3d,
    plot_raster,
    plot_population_rate,
    plot_membrane_potentials,
    plot_lfp,
    plot_csd,
    plot_psd,
    plot_spectrogram,
    plot_band_power,
    plot_depth_profile,
    plot_connectivity,
    plot_objective_history,
)
from .exporters import export_figure, export_figures, FigureBundle
from .script_reports import (
    column_network_3d_scatter,
    column_readout_panels,
    rate_histogram_by_celltype,
    sweep_rate_lines,
    spectrolaminar_motif_heatmap,
    spike_triggered_waveforms_plot,
    hdp_state_trajectories,
    rate_vs_pressure_scatter,
    hdp_H_occupancy_histogram,
    hdp_stability_map,
    tutorial_spike_raster,
    tutorial_voltage_traces,
    tutorial_matrix_heatmap,
    tutorial_lfp_proxy_trace,
    tutorial_conservation_bar,
    tutorial_contact_depths_barh,
    tutorial_status_text_panel,
    tutorial_spectral_summary,
    spike_raster_plotly,
    spectrolaminar_profile_bars_plotly,
    tutorial_spike_raster_vlines_plotly,
    tutorial_voltage_trace_plotly,
    tutorial_firing_rate_plotly,
)
from .hdp_diagnostics import (
    synaptic_channel_decomposition_trace,
    dH_component_trace_panels,
    bifurcation_state_trace_panels,
    gain_ratio_sweep_panels,
    balance_sweep_by_network_size,
    lfp_traces_stacked_by_depth,
    etude2_extended_panel_grid,
    voltage_trace_with_spikes_by_celltype,
)
from .report_plots import (
    dual_raster_comparison,
    optimization_progress_line,
    spike_grid_heatmap,
    signed_heatmap_with_colorbar,
    grouped_bar_comparison,
    agsdr_rate_tuning_panel_grid,
    open_pdf_pages,
    pdf_text_page,
    pdf_figure_page,
    gain_matrix_heatmap,
    celltype_sweep_heatmap_grid,
)

__all__ = [
    "FigureResult",
    "require_matplotlib",
    "prepare_static_plot_matrix",
    "close_all",
    "plot_spike_rasters",
    "raster",
    "raster_with_meta",
    "plot_continuous_traces",
    "vm",
    "vm_with_meta",
    "rate",
    "rate_with_meta",
    "source",
    "source_with_meta",
    "lfp",
    "lfp_with_meta",
    "csd",
    "csd_with_meta",
    "lfp_traces",
    "csd_traces",
    "eeg",
    "meg",
    "emm",
    "summary",
    "summary_with_meta",
    "parameter_sweep_heatmap",
    "parameter_sweep_lines",
    "multi_trace",
    "dual_voltage_panel",
    "coupled_vs_uncoupled_ei",
    "plot_spectrogram_profiles",
    "psd",
    "psd_with_meta",
    "spectrogram",
    "spectrogram_with_meta",
    "windowed_band_power",
    "plot_laminar_field_interpolation",
    "spectrolaminar",
    "spectrolaminar_suite",
    "bandpower",
    "laminar_profile",
    "layer_celltype_counts",
    "connectivity",
    "connectivity_matrix",
    "multi_area_layout",
    "objective_report",
    "ei_circuit_diagram",
    "circuit3d",
    "geometry3d",
    "column_geometry",
    "visualize_network_3d",
    # Tutorial panels (Etude No. 1)
    "visualize_laminar_column_3d",
    "activity_trace_suite",
    "spectrolaminar_suite_3panel",
    "raster_from_arrays",
    "plot_stdp_adaptation_suite",
    "cumulative_stack_offsets",
    "cumulative_panel_extents",
    "plot_population_raster",
    "plot_population_rate_array",
    "plot_voltage_samples_array",
    "plot_connectivity_matrix_array",
    "plot_laminar_readout_array",
    "plot_spectrolaminar_power_array",
    # Canonical backend-dispatching entry points (default backend="plotly")
    "plotly",
    "plot_network_3d",
    "plot_raster",
    "plot_population_rate",
    "plot_membrane_potentials",
    "plot_lfp",
    "plot_csd",
    "plot_psd",
    "plot_spectrogram",
    "plot_band_power",
    "plot_depth_profile",
    "plot_connectivity",
    "plot_objective_history",
    "export_figure",
    "export_figures",
    "FigureBundle",
    # script_reports (scripts/*.py rendering helpers)
    "column_network_3d_scatter",
    "column_readout_panels",
    "rate_histogram_by_celltype",
    "sweep_rate_lines",
    "spectrolaminar_motif_heatmap",
    "spike_triggered_waveforms_plot",
    "hdp_state_trajectories",
    "rate_vs_pressure_scatter",
    "hdp_H_occupancy_histogram",
    "hdp_stability_map",
    "tutorial_spike_raster",
    "tutorial_voltage_traces",
    "tutorial_matrix_heatmap",
    "tutorial_lfp_proxy_trace",
    "tutorial_conservation_bar",
    "tutorial_contact_depths_barh",
    "tutorial_status_text_panel",
    "tutorial_spectral_summary",
    "spike_raster_plotly",
    "spectrolaminar_profile_bars_plotly",
    "tutorial_spike_raster_vlines_plotly",
    "tutorial_voltage_trace_plotly",
    "tutorial_firing_rate_plotly",
    # hdp_diagnostics (scripts/hdp_*.py + scripts/{find,verify}_5hz_*.py rendering helpers)
    "synaptic_channel_decomposition_trace",
    "dH_component_trace_panels",
    "bifurcation_state_trace_panels",
    "gain_ratio_sweep_panels",
    "balance_sweep_by_network_size",
    "lfp_traces_stacked_by_depth",
    "etude2_extended_panel_grid",
    "voltage_trace_with_spikes_by_celltype",
    "dual_raster_comparison",
    "optimization_progress_line",
    "spike_grid_heatmap",
    "signed_heatmap_with_colorbar",
    "grouped_bar_comparison",
    "agsdr_rate_tuning_panel_grid",
    "open_pdf_pages",
    "pdf_text_page",
    "pdf_figure_page",
    "gain_matrix_heatmap",
    "celltype_sweep_heatmap_grid",
]
