"""Fields subpackage for jaxfne.

Isolates localized laminar projection computations from higher-level multimodal probe transformations.
"""
from __future__ import annotations

from .proxy import (
    FieldOutput,
    project_laminar_sources,
    project_sources_to_laminar_field,
    validate_projection_invariants,
    validate_source_field_status,
    compute_conservation_proxy_diagnostics,
    probe_laminar_modes,
    make_laminar_connectivity,
    exponential_synaptic_trace,
    synaptic_current,
    filtered_spike_source,
    teaching_control_spectrolaminar_resonance_source,
    spectrolaminar_psd,
    spectrolaminar_bandpower,
    spectrolaminar_readout,
    multi_area_spectrolaminar_readout,
    LinearReadout,
    construct_source_tensor,
    synaptic_resonance_source,
    combined_multi_area_source,
    spectrolaminar_similarity,
    spectrolaminar_objective,
    _make_field_solution_report,
)
from .probes import (
    ProbeReadout,
    spk_probe,
    vm_probe,
    source_probe,
    lfp_proxy_probe,
    csd_proxy_probe,
    eeg_proxy_probe,
    meg_proxy_probe,
    emm_proxy_probe,
    eeg_proxy_transform,
    meg_proxy_transform,
    emm_proxy_transform,
)

__all__ = [
    "FieldOutput",
    "project_laminar_sources",
    "project_sources_to_laminar_field",
    "validate_projection_invariants",
    "validate_source_field_status",
    "compute_conservation_proxy_diagnostics",
    "probe_laminar_modes",
    "make_laminar_connectivity",
    "exponential_synaptic_trace",
    "synaptic_current",
    "filtered_spike_source",
    "teaching_control_spectrolaminar_resonance_source",
    "spectrolaminar_psd",
    "spectrolaminar_bandpower",
    "spectrolaminar_readout",
    "multi_area_spectrolaminar_readout",
    "LinearReadout",
    "construct_source_tensor",
    "synaptic_resonance_source",
    "combined_multi_area_source",
    "spectrolaminar_similarity",
    "spectrolaminar_objective",
    "_make_field_solution_report",
    "ProbeReadout",
    "spk_probe",
    "vm_probe",
    "source_probe",
    "lfp_proxy_probe",
    "csd_proxy_probe",
    "eeg_proxy_probe",
    "meg_proxy_probe",
    "emm_proxy_probe",
    "eeg_proxy_transform",
    "meg_proxy_transform",
    "emm_proxy_transform",
]
