"""Experimental HPC/JAX architecture contracts for future jaxfne releases.

These symbols are not part of the stable public API. They exist to document the
planned tensor-first architecture and to fail loudly until implemented.
"""

from .contracts import (
    Config,
    RuntimeStatic,
    CircuitSpec,
    ProbeSpec,
    NodeIdentity,
    SelectorSpec,
    MechanismSpec,
    WeightInitSpec,
    ConnectionRuleSpec,
    ConnectionCompileResult,
    Net,
    FlatNet,
    TrackingMaps,
    SignalTensor,
    Signals,
    Paradigm,
    ObjectiveOutputSpec,
    ObjectiveResult,
    Trainer,
    TrainingResult,
    compile_connection_rules,
    construct_net,
    flatten_net,
    unflatten_net,
    simulate_flat_izhikevich,
    weld_config,
    get_signal,
)
from .physical_field_solver_v040 import (
    PhysicalFieldSolverSpec,
    solve_physical_field,
)

__all__ = [
    "Config",
    "RuntimeStatic",
    "CircuitSpec",
    "ProbeSpec",
    "NodeIdentity",
    "SelectorSpec",
    "MechanismSpec",
    "WeightInitSpec",
    "ConnectionRuleSpec",
    "ConnectionCompileResult",
    "Net",
    "FlatNet",
    "TrackingMaps",
    "SignalTensor",
    "Signals",
    "Paradigm",
    "ObjectiveOutputSpec",
    "ObjectiveResult",
    "Trainer",
    "TrainingResult",
    "compile_connection_rules",
    "construct_net",
    "flatten_net",
    "unflatten_net",
    "simulate_flat_izhikevich",
    "weld_config",
    "get_signal",
    "PhysicalFieldSolverSpec",
    "solve_physical_field",
]
