"""jaxfne: JAX Field Neural Equations.

A compact source-to-field neurophysiology engine for Tensor-Field Neural
Equations (TFNE).  Public API is object-oriented; numerical kernels are JAX-first.
"""

from .core import (
    Configuration,
    DatasetSpec,
    LaminarPopulation,
    LaminarSourceGeometry,
    Model,
    Objective,
    Paradigm,
    ParadigmCondition,
    ParadigmEvent,
    Probe,
    RuntimeConfig,
    Signal,
    Signals,
    Simulation,
    StimulusSchedule,
    SurrogateConfig,
    TrialBatch,
    TrialBatchResult,
    TrialResult,
    TrialSpec,
    configuration,
    construct,
    dataset_spec,
    enable_x64,
    laminar_source_geometry,
    objective,
    operator_status,
    paradigm,
    runtime,
    runtime_report,
    run_trials,
    simulation,
    standard_visual_omission,
    stimulus_schedule,
    surrogate_config,
    trial_batch,
    _KNOWN_METRICS,
)
from .bridges import BridgeSpec, JaxleyEmitterBridge, require_jaxley
from .emitters import (
    EdgeList,
    EIGNetwork,
    IzhikevichParams,
    ReceptorSpec,
    SynapseSpec,
    make_edge_list_from_dense,
    make_eig_network,
    simulate_edge_recurrent_izhikevich,
    simulate_eig_izhikevich,
    simulate_receptor_exponential_izhikevich,
    standard_receptor_specs,
    standard_receptor_tau_table,
)
from .fields import (
    FieldOutput,
    project_laminar_sources,
    project_sources_to_laminar_field,
    probe_laminar_modes,
    validate_projection_invariants,
    validate_source_field_status,
)
from .io import config_hash, json_safe, manifest, save_json, sha256_file, sha256_text
from .optim import (
    AGSDR,
    OptimizerSpec,
    agsdr,
    gsdr,
    optax_adam,
    optax_sgd,
    random_search,
    require_optax,
)

__all__ = [
    "BridgeSpec",
    "Configuration",
    "DatasetSpec",
    "JaxleyEmitterBridge",
    "LaminarPopulation",
    "LaminarSourceGeometry",
    "Model",
    "Objective",
    "Paradigm",
    "ParadigmCondition",
    "ParadigmEvent",
    "Probe",
    "RuntimeConfig",
    "Signal",
    "Signals",
    "Simulation",
    "StimulusSchedule",
    "SurrogateConfig",
    "TrialBatch",
    "TrialBatchResult",
    "TrialResult",
    "TrialSpec",
    "configuration",
    "construct",
    "dataset_spec",
    "enable_x64",
    "laminar_source_geometry",
    "objective",
    "operator_status",
    "paradigm",
    "require_jaxley",
    "runtime",
    "runtime_report",
    "run_trials",
    "simulation",
    "standard_visual_omission",
    "stimulus_schedule",
    "surrogate_config",
    "trial_batch",
    "_KNOWN_METRICS",
    "EdgeList",
    "EIGNetwork",
    "IzhikevichParams",
    "ReceptorSpec",
    "SynapseSpec",
    "make_edge_list_from_dense",
    "make_eig_network",
    "simulate_edge_recurrent_izhikevich",
    "simulate_eig_izhikevich",
    "simulate_receptor_exponential_izhikevich",
    "standard_receptor_specs",
    "standard_receptor_tau_table",
    "FieldOutput",
    "project_laminar_sources",
    "project_sources_to_laminar_field",
    "probe_laminar_modes",
    "validate_projection_invariants",
    "validate_source_field_status",
    "config_hash",
    "json_safe",
    "manifest",
    "save_json",
    "sha256_file",
    "sha256_text",
    "AGSDR",
    "OptimizerSpec",
    "agsdr",
    "gsdr",
    "optax_adam",
    "optax_sgd",
    "random_search",
    "require_optax",
]

__version__ = "0.0.14"
