"""jaxfne: JAX Field Neural Equations.

A compact source-to-field neurophysiology engine for Tensor-Field Neural
Equations (TFNE).  Public API is object-oriented; numerical kernels are JAX-first.
"""

from .core import (
    Configuration,
    DatasetSpec,
    Model,
    Objective,
    Paradigm,
    ParadigmCondition,
    ParadigmEvent,
    Probe,
    RuntimeConfig,
    Signal,
    Signals,
    Simulation,
    SurrogateConfig,
    configuration,
    construct,
    dataset_spec,
    enable_x64,
    objective,
    operator_status,
    paradigm,
    runtime,
    runtime_report,
    simulation,
    standard_visual_omission,
    surrogate_config,
    _KNOWN_METRICS,
)
from .bridges import BridgeSpec, JaxleyEmitterBridge, require_jaxley
from .emitters import EIGNetwork, IzhikevichParams, make_eig_network, simulate_eig_izhikevich
from .fields import (
    FieldOutput,
    project_laminar_sources,
    project_sources_to_laminar_field,
    probe_laminar_modes,
    validate_projection_invariants,
    validate_source_field_status,
)
from .io import config_hash, json_safe, manifest, save_json, sha256_file, sha256_text
from .optim import (
    AGSDR,
    OptimizerSpec,
    agsdr,
    gsdr,
    optax_adam,
    optax_sgd,
    random_search,
    require_optax,
)

__all__ = [
    "BridgeSpec",
    "Configuration",
    "DatasetSpec",
    "JaxleyEmitterBridge",
    "Model",
    "Objective",
    "Paradigm",
    "ParadigmCondition",
    "ParadigmEvent",
    "Probe",
    "RuntimeConfig",
    "Signal",
    "Signals",
    "Simulation",
    "SurrogateConfig",
    "configuration",
    "construct",
    "dataset_spec",
    "enable_x64",
    "objective",
    "operator_status",
    "paradigm",
    "require_jaxley",
    "runtime",
    "runtime_report",
    "simulation",
    "standard_visual_omission",
    "surrogate_config",
    "_KNOWN_METRICS",
    "EIGNetwork",
    "IzhikevichParams",
    "make_eig_network",
    "simulate_eig_izhikevich",
    "FieldOutput",
    "project_laminar_sources",
    "project_sources_to_laminar_field",
    "probe_laminar_modes",
    "validate_projection_invariants",
    "validate_source_field_status",
    "config_hash",
    "json_safe",
    "manifest",
    "save_json",
    "sha256_file",
    "sha256_text",
    "AGSDR",
    "OptimizerSpec",
    "agsdr",
    "gsdr",
    "optax_adam",
    "optax_sgd",
    "random_search",
    "require_optax",
]

__version__ = "0.0.8"
