"""Generate the 0.5.5 methods table from the Atlas result files (todo item 12).

Every value is read from ``artifacts/atlas/results/*.json``; nothing is typed
by hand. Usage: ``python scripts/gen_methods_055.py`` rewrites
``artifacts/programme/methods_055.md``; ``--check`` exits 1 if it is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import jaxfne  # noqa: E402

assert "site-packages" not in sys.modules["jaxfne"].__file__, (
    "P-025: expected the repo jaxfne on sys.path, not site-packages"
)

RES = ROOT / "artifacts" / "atlas" / "results"
OUT = ROOT / "artifacts" / "programme" / "methods_055.md"
TOL_KEYS = ("tolerances_predeclared", "tolerance_predeclared", "verdict_tolerances_predeclared")
SEED_KEYS = ("noise_seed", "seed", "seeds")
# Level/seed fields that actually occur in the atlas results beyond the top
# level: at10_n20_055.json declares its level and noise seed under `spec`,
# at01_055.json declares its level under `reduced`. No result file carries a
# units field (the string "units" appears only inside prose notes), and no
# result file for the dashed at10 rows carries `_meta`, so no units column is
# added and recorded versions stay dashed for those rows.
LEVEL_PATHS = (("level",), ("spec", "level"), ("reduced", "level"))
SEED_PATHS = (("noise_seed",), ("seed",), ("seeds",), ("spec", "noise", "seed"))


def _nested(d: dict, path: tuple[str, ...]):
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return None
        cur = cur[key]
    return cur


def _first(d: dict, keys: tuple[str, ...]):
    for k in keys:
        if k in d:
            return d[k]
    return None


def _row(path: Path) -> str:
    d = json.loads(path.read_text(encoding="utf-8"))
    meta = d.get("_meta", {})
    tol = _first(d, TOL_KEYS)
    seed, seed_path = None, None
    for path_keys in SEED_PATHS:
        value = _nested(d, path_keys)
        if value is not None:
            seed, seed_path = value, path_keys
            break
    level = next(
        (value for value in (_nested(d, p) for p in LEVEL_PATHS) if value is not None),
        None,
    )
    if seed is None:
        seed_cell = "-"
    elif seed_path in ((k,) for k in SEED_KEYS):
        seed_cell = json.dumps(seed)
    else:
        seed_cell = ".".join(seed_path) + "=" + json.dumps(seed)
    cells = [
        f"`{path.name}`",
        str(d.get("scenario", "")) or "-",
        str(level) if level is not None else "-",
        json.dumps(tol, sort_keys=True) if tol is not None else "-",
        seed_cell,
        str(meta.get("jaxfne_version", "-")),
        str(meta.get("runner", "-")),
    ]
    return "| " + " | ".join(cells) + " |"


def render() -> str:
    lines = [
        "# Methods table (generated)",
        "",
        "Generated by `python scripts/gen_methods_055.py` from "
        "`artifacts/atlas/results/*.json`; do not edit by hand. A dash means "
        "the result file carries no such field. Calibration level is the file's "
        "declared `level` (top-level, `spec.level`, or `reduced.level`; "
        "RELATIVE_PROXY / REDUCED_PHYSICAL); no value is calibrated. The seed "
        "column quotes the file's noise seed: top-level `noise_seed`/`seed`, "
        "or `spec.noise.seed` shown as path=value when nested. The recorded "
        "jaxfne version and runner come from `_meta` only.",
        "",
        f"Generator ran against jaxfne {jaxfne.__version__}.",
        "",
        "| result file | scenario | level | predeclared tolerances | seed | jaxfne (recorded) | runner |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [_row(p) for p in sorted(RES.glob("*.json"))]
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        print("methods_055 current" if ok else "methods_055 STALE")
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
