"""Generate the 0.5.5 methods table from the Atlas result files (todo item 12).

Every value is read from ``artifacts/atlas/results/*.json``; nothing is typed
by hand. Usage: ``python scripts/gen_methods_055.py`` rewrites
``artifacts/programme/methods_055.md``; ``--check`` exits 1 if it is stale.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import jaxfne  # noqa: E402

assert "site-packages" not in sys.modules["jaxfne"].__file__, (
    "P-025: expected the repo jaxfne on sys.path, not site-packages"
)

RES = ROOT / "artifacts" / "atlas" / "results"
OUT = ROOT / "artifacts" / "programme" / "methods_055.md"
TOL_KEYS = ("tolerances_predeclared", "tolerance_predeclared", "verdict_tolerances_predeclared")
SEED_KEYS = ("noise_seed", "seed", "seeds")


def _first(d: dict, keys: tuple[str, ...]):
    for k in keys:
        if k in d:
            return d[k]
    return None


def _row(path: Path) -> str:
    d = json.loads(path.read_text(encoding="utf-8"))
    meta = d.get("_meta", {})
    tol = _first(d, TOL_KEYS)
    seed = _first(d, SEED_KEYS)
    cells = [
        f"`{path.name}`",
        str(d.get("scenario", "")),
        str(d.get("level", "")),
        json.dumps(tol, sort_keys=True) if tol is not None else "-",
        json.dumps(seed) if seed is not None else "-",
        str(meta.get("jaxfne_version", "-")),
        str(meta.get("runner", "-")),
    ]
    return "| " + " | ".join(cells) + " |"


def render() -> str:
    lines = [
        "# Methods table (generated)",
        "",
        "Generated by `python scripts/gen_methods_055.py` from "
        "`artifacts/atlas/results/*.json`; do not edit by hand. A dash means "
        "the result file carries no such field. Calibration level is the file's "
        "`level` (RELATIVE_PROXY / REDUCED_PHYSICAL); no value is calibrated.",
        "",
        f"Generator ran against jaxfne {jaxfne.__version__}.",
        "",
        "| result file | scenario | level | predeclared tolerances | seed | jaxfne (recorded) | runner |",
        "|---|---|---|---|---|---|---|",
    ]
    lines += [_row(p) for p in sorted(RES.glob("*.json"))]
    return "\n".join(lines) + "\n"


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        print("methods_055 current" if ok else "methods_055 STALE")
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
